#!/usr/bin/env python3
"""Pack ArrowOut level JSON files into levels.js for ArrowOut Level Studio.

Usage:
    python3 tools/pack_levels.py <folder with level_*.json> > levels.js

Input (one file per level, game format):
    {"width": W, "height": H, "timer": {"seconds": S, ...},
     "pieces": [{"id": ..., "dir": "up|down|left|right", "color": "#RRGGBB",
                 "cells": [{"x": .., "y": ..}, ...]}, ...]}
    The first cell is the head; Y grows upwards.

Output:
    window.PACKED_LEVELS = {"c": [palette], "l": {"<number>": {"w", "h", "t", "p"}}};
    where each entry of "p" is [colorIndex, dirLetter, headX, headY, moves] and
    moves is one letter per following cell relative to the previous one:
    R=(+1,0) L=(-1,0) U=(0,+1) D=(0,-1) in game coordinates (no Y flip).
"""
import json
import os
import re
import sys

DIR_LETTER = {"up": "U", "down": "D", "left": "L", "right": "R"}
MOVE_LETTER = {(1, 0): "R", (-1, 0): "L", (0, 1): "U", (0, -1): "D"}
NUMBER_RE = re.compile(r"(\d+)")


def level_number(file_name):
    digits = NUMBER_RE.findall(file_name)
    if not digits:
        raise ValueError("no level number in file name: %s" % file_name)
    return int(digits[-1])


def encode_moves(cells, file_name, piece_id):
    moves = []
    for prev, cur in zip(cells, cells[1:]):
        step = (cur["x"] - prev["x"], cur["y"] - prev["y"])
        if step not in MOVE_LETTER:
            raise ValueError("%s: piece %s has non-adjacent cells %s -> %s"
                             % (file_name, piece_id, prev, cur))
        moves.append(MOVE_LETTER[step])
    return "".join(moves)


def pack_piece(piece, palette, file_name):
    color = piece.get("color") or "#888888"
    if color not in palette:
        palette.append(color)
    direction = piece.get("dir", "up")
    if direction not in DIR_LETTER:
        raise ValueError("%s: piece %s has unknown dir %r" % (file_name, piece.get("id"), direction))
    cells = piece.get("cells") or []
    if not cells:
        raise ValueError("%s: piece %s has no cells" % (file_name, piece.get("id")))
    head = cells[0]
    return [palette.index(color), DIR_LETTER[direction], head["x"], head["y"],
            encode_moves(cells, file_name, piece.get("id"))]


def pack_level(path, palette):
    file_name = os.path.basename(path)
    with open(path, encoding="utf-8") as handle:
        level = json.load(handle)
    timer = level.get("timer") or {}
    return {
        "w": level["width"],
        "h": level["height"],
        "t": timer.get("seconds", 0),
        "p": [pack_piece(piece, palette, file_name) for piece in level.get("pieces", [])],
    }


def pack_folder(folder):
    palette = []
    levels = {}
    names = sorted(n for n in os.listdir(folder) if n.lower().endswith(".json"))
    for name in names:
        number = level_number(name)
        levels[str(number)] = pack_level(os.path.join(folder, name), palette)
    ordered = {key: levels[key] for key in sorted(levels, key=int)}
    return {"c": palette, "l": ordered}


def main(argv):
    if len(argv) != 2 or not os.path.isdir(argv[1]):
        sys.stderr.write(__doc__)
        return 2
    packed = pack_folder(argv[1])
    sys.stdout.write("// Generated by tools/pack_levels.py from %d level files.\n"
                     % len(packed["l"]))
    sys.stdout.write("window.PACKED_LEVELS = %s;\n"
                     % json.dumps(packed, separators=(",", ":"), ensure_ascii=False))
    sys.stderr.write("packed %d levels, %d colors\n" % (len(packed["l"]), len(packed["c"])))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
